### ISSUE TITLE
Checking out projects:   0% (3/747) platform/bootable/recoveryerror: unable to create file pathtools/testdata/escapes/*: Argomento non valido

### ISSUE THREAD

**Issue by Marietto2008** [antmicro/kvm-aosp-jetson-nano#13]
Checking out projects:   0% (3/747) platform/bootable/recoveryerror: unable to create file pathtools/testdata/escapes/*: Argomento non valido
fatal: cannot create directory at 'pathtools/testdata/escapes/**': Argomento non valido
error: Cannot checkout platform/build/blueprint: GitError: Cannot initialize work tree for platform/build/blueprint
Traceback (most recent call last):
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/main.py", line 627, in <module>
    _Main(sys.argv[1:])
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/main.py", line 601, in _Main
    result = run()
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/main.py", line 594, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/main.py", line 260, in _Run
    result = cmd.Execute(copts, cargs)
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/subcmds/sync.py", line 964, in Execute
    self._Checkout(all_projects, opt, err_event, err_results)
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/subcmds/sync.py", line 548, in _Checkout
    self._CheckoutWorker(**kwargs)
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/subcmds/sync.py", line 428, in _CheckoutWorker
    return self._CheckoutOne(opt, project, *args, **kwargs)
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/subcmds/sync.py", line 462, in _CheckoutOne
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/project.py", line 1211, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "/media/ziomario/Elements/Backups/Nano/kvm-aosp-jetson-nano/aosp/.repo/repo/project.py", line 2751, in _InitWorkTree
    raise GitError('Cannot initialize work tree for ' + self.name)
error.GitError: Cannot initialize work tree for platform/build/blueprint

**Comment by pgielda** [comment]
Please open issues in English with a proper description only. I am closing this one.
